# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'
    workingDir: 'frontend'
- task: CmdLine@2
  displayName: 'npm run'
  inputs:
    script: 'npm run'
    workingDirectory: 'frontend'
- task: DotNetCoreCLI@2
  displayName: '.NET Core Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(ProjectPath)/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    feedsToUse: 'select'
    versioningScheme: 'off'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'